### ISSUE TITLE
No High Sierra Bottle

### ISSUE THREAD

**Issue by whitj00** [KryptCo/bottles#1]
I tried to install Kryptonite on the high sierra beta but it failed due to the lack of a high sierra bottle

**Comment by kcking** [comment]
Hi Whit, we will bottle for high-sierra within the next couple of days. In the meantime, you should be able to install from source using `brew install --HEAD kryptco/tap/kr`

Let us know if this works for you!

**Comment by kcking** [comment]
rather, until we've updated our install script, this is the brew command to run: `brew install --force-bottle kryptco/tap/kr`

**Comment by kcking** [comment]
We now bottle for high_sierra  as well :)
